name: sing_plugin_tools
description: "各种flutter的小插件、工具"
version: 0.0.22
homepage: https://github.com/flutter-open-libs/flutter_plugin_tools

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  get: ^4.6.6
  logger: ^2.3.0
  get_storage: ^2.0.3 # 本地存储插件get_storage,https://pub.dev/packages/get_storage
  flutter_screenutil: ^5.9.0
  dio: ^5.4.3+1
  flutter_easyloading: ^3.0.5 # https://pub.dev/packages/flutter_easyloading loading窗口
  cached_network_image: ^3.4.1 # 带缓存的图片加载，https://pub.dev/packages/cached_network_image

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: sing.top.plugin_tools
        pluginClass: SingPluginToolsPlugin
      ios:
        pluginClass: SingPluginToolsPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages